### ISSUE TITLE
[진행현황] API 개발 현황 리스트

### ISSUE THREAD

**Issue by LeahJiinLee** [hscom96/11st-board-practice#38]
# 1. 게시글 관련

- [x] 게시글 등록
- [x] 게시글 수정
- [x] 게시글 삭제

# 2. 댓글 관련

# 3. 반응하기 기능

# 4. 회원가입

# 5. 로그인

**Comment by djkeh** [comment]
@LeahJiinLee 요거는 프로젝트에는 관리되고 있지 않은 이슈네요?
